import os
import datetime

os.makedirs('project-context/profiles', exist_ok=True)

date_str = datetime.datetime.now().strftime('%Y-%m-%d')

template = """# Profile {idx}: {title}

> Auto-generated by Project Scanner Agent
> Scanned: {date}

## 1. Overview
{overview}

## 2. Current Implementation
### 2.1 {sub_section}
{details}

## 3. Patterns & Conventions
{patterns}

## 4. Dependencies
{deps}

## 5. Gaps & Recommendations
{gaps}

## 6. Key Files
{key_files}
"""

profiles = [
    {
        "file": "01-architecture.md",
        "title": "Architecture",
        "overview": "The project follows Clean Architecture principles, separated into Domain, Data, and UI layers. It relies heavily on a custom Excel ORM for data persistence over Google Drive.",
        "sub_section": "Clean Architecture Implementation",
        "details": "The application segregates responsibilities cleanly. `lib/domain/` houses business rules (models, repositories interfaces, use cases). `lib/data/` contains repository implementations and services, particularly a custom ORM in `lib/data/orm/` for Google Sheets. `lib/ui/` is split into `core/` (shared widgets, theme) and `features/` (feature-based organization with views and view models).",
        "patterns": "- **Clean Architecture**: Domain, Data, and UI separation.\n- **Repository Pattern**: Abstract interfaces in Domain, implemented in Data layer.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| googleapis | ^11.0.0 | Google Drive API integration |\n| excel | ^2.1.0 | Parsing and creating Excel files for ORM |",
        "gaps": "- [ ] Dependency injection setup is not explicitly visible (e.g., get_it or provider).",
        "key_files": "| File | Purpose |\n|---|---|\n| [main.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/main.dart) | Application entry point |\n| [excel_context.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/data/orm/excel_context.dart) | ORM context base |"
    },
    {
        "file": "02-navigation.md",
        "title": "Navigation",
        "overview": "The app uses standard Flutter imperative navigation (Navigator 1.0) with standard MaterialPageRoute pushes.",
        "sub_section": "Routing Approach",
        "details": "Navigation is handled via `Navigator.of(context).push(...)` as seen in `lib/ui/features/workout_split/views/workout_split_page.dart`. There is no advanced routing package like go_router or auto_route currently employed.",
        "patterns": "- **Imperative Navigation**: Direct use of `Navigator.push` and `Navigator.pop`.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| flutter | sdk | Standard navigation framework |",
        "gaps": "- [ ] Transition to declarative routing (e.g. go_router) for deep linking and cleaner route management.",
        "key_files": "| File | Purpose |\n|---|---|\n| [workout_split_page.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/ui/features/workout_split/views/workout_split_page.dart) | Navigation implementation example |"
    },
    {
        "file": "03-state.md",
        "title": "State Management",
        "overview": "State management utilizes Flutter's native `ValueNotifier` and `StatefulWidget` for local state, and ViewModels combined with UseCases for business logic.",
        "sub_section": "View Models and Value Notifiers",
        "details": "The UI components observe state changes typically through `ValueNotifier`. For example, `AuthAndSyncUseCase` exposes a `syncStateNotifier`. Many UI components are stateful widgets managing their own internal state (e.g. `_isLoading`, `_schedule`).",
        "patterns": "- **ViewModel / UseCase Mapping**: UI binds to ViewModels or directly to UseCases.\n- **ValueNotifier**: Used for reactive state sharing without heavyweight packages.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| flutter | sdk | Native state management |",
        "gaps": "- [ ] Lack of a unified state management solution (like Riverpod or Bloc) could lead to prop drilling or lifecycle issues as complexity grows.",
        "key_files": "| File | Purpose |\n|---|---|\n| [auth_and_sync_use_case.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/domain/use_cases/auth_and_sync_use_case.dart) | Sync state management |"
    },
    {
        "file": "04-testing.md",
        "title": "Testing",
        "overview": "The project includes robust unit and widget testing, testing both the UI behavior and the domain/data logic.",
        "sub_section": "Test Coverage",
        "details": "Tests are located in `test/`. Widget tests mock UI interactions (e.g., `AddWorkoutSetModal`, `HomeScreen`, `WorkoutSplitPage`), verifying form validation and state updates. Unit tests presumably cover the Excel ORM (`test/excel_orm_test.dart`) and statistics logic (`test/exercise_statistics_test.dart`).",
        "patterns": "- **Widget Testing**: using `flutter_test` for verifying UI logic.\n- **Mocking**: `SharedPreferences.setMockInitialValues` used for local storage mocks.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| flutter_test | sdk | Testing framework |",
        "gaps": "- [ ] No integration tests (e.g. integration_test package) found for end-to-end user flows.",
        "key_files": "| File | Purpose |\n|---|---|\n| [features_and_optimizations_test.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/test/features_and_optimizations_test.dart) | Example widget tests |"
    },
    {
        "file": "05-security.md",
        "title": "Security",
        "overview": "The application secures data by leveraging Google Sign-In and Google Drive API for authenticated data storage.",
        "sub_section": "Authentication and Data Storage",
        "details": "Authentication is handled via `google_sign_in`. User data is stored in their personal Google Drive as Excel sheets, ensuring data privacy and ownership. Credentials or API keys should be injected at build time (avoiding commits).",
        "patterns": "- **OAuth2 Authentication**: Google Sign-in integration.\n- **BYOS (Bring Your Own Storage)**: Uses user's Google Drive.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| google_sign_in | ^6.0.0 | User authentication |",
        "gaps": "- [ ] Verify OAuth scopes are strictly limited to necessary files (e.g., `drive.file` scope).",
        "key_files": "| File | Purpose |\n|---|---|\n| [google_drive_service.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/data/services/google_drive_service.dart) | Google Drive integration |"
    },
    {
        "file": "06-performance.md",
        "title": "Performance",
        "overview": "Performance is generally good, optimized by using localized caching and efficient Excel file manipulation.",
        "sub_section": "Data Caching",
        "details": "The repository implementation heavily caches queries. `getCachedTodaysWorkoutEntries` and `getCachedExercises` are provided by `GetTodaysWorkoutUseCase` and `ManageExercisesUseCase` respectively, indicating UI doesn't always hit the Google Drive backend, minimizing network overhead.",
        "patterns": "- **Local Caching**: Reduces cloud sync frequency.\n- **Lazy Loading**: `ValueNotifier` prevents full tree rebuilds.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| shared_preferences | ^2.5.3 | Local caching of split choices |",
        "gaps": "- [ ] The Excel parsing might become a bottleneck on very large datasets; consider chunked loading or background isolates.",
        "key_files": "| File | Purpose |\n|---|---|\n| [get_todays_workout_use_case.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/domain/use_cases/get_todays_workout_use_case.dart) | Caching usage |"
    },
    {
        "file": "07-error-handling.md",
        "title": "Error Handling",
        "overview": "The application incorporates basic error states for network and data operations, reflected in the UI.",
        "sub_section": "Sync State Errors",
        "details": "Sync states (like `SyncState.error`) are propagated to the UI. The `CompactSyncButton` and error banners update automatically when sync fails. Form validations ensure data integrity (e.g., validating reps > 0 in `AddWorkoutSetModal`).",
        "patterns": "- **Form Validation**: UI-level error prevention.\n- **Stateful Error UI**: Displaying specific widgets based on error states.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| N/A | N/A | Built-in mechanisms |",
        "gaps": "- [ ] Centralized error reporting (e.g. Crashlytics or Sentry) is missing.",
        "key_files": "| File | Purpose |\n|---|---|\n| [add_workout_set_modal.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/ui/features/workout_log/views/widgets/add_workout_set_modal.dart) | Validation handling |"
    },
    {
        "file": "08-typescript.md",
        "title": "Language & Type System",
        "overview": "The project is written in Dart, taking full advantage of sound null safety and strongly-typed models.",
        "sub_section": "Dart Features",
        "details": "The custom Excel ORM uses Dart Generics extensively (e.g., `ExcelTable<T>`, `ExcelQuery<T>`). Models are strictly typed and null-safety is properly maintained throughout the data mapping process.",
        "patterns": "- **Generics**: Used for flexible ORM implementations.\n- **Sound Null Safety**: Safely parsing dynamic row data from Excel sheets.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| dart | ^3.13.2 | Language |",
        "gaps": "- [ ] Consider using code generation (like Freezed or json_serializable) to reduce manual mapping boilerplate.",
        "key_files": "| File | Purpose |\n|---|---|\n| [excel_query.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/data/orm/excel_query.dart) | Advanced generics usage |"
    },
    {
        "file": "09-component-design.md",
        "title": "Component Design",
        "overview": "UI components are modular and decoupled, following atomic design principles within the `lib/ui/core/widgets` directory.",
        "sub_section": "Core Widgets",
        "details": "Reusable components like `ModularCard`, `StatusBadge`, and `AnimatedLoadingWindow` are used consistently across features. Feature-specific widgets are neatly scoped within their respective feature folders (e.g. `lib/ui/features/workout_log/views/widgets/`).",
        "patterns": "- **Modular Widgets**: High reuse of UI components.\n- **Theming**: Driven by `AppTheme` and `AppColors`.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| flutter | sdk | Core UI framework |",
        "gaps": "- [ ] Missing Storybook-like documentation for UI components.",
        "key_files": "| File | Purpose |\n|---|---|\n| [modular_card.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/ui/core/widgets/modular_card.dart) | Core UI component |"
    },
    {
        "file": "10-accessibility.md",
        "title": "Accessibility",
        "overview": "Accessibility features appear to rely mostly on standard Flutter Material widget capabilities.",
        "sub_section": "Semantics",
        "details": "The app uses standard text, buttons, and dialogs. Further inspection is needed to verify if semantic labels are explicitly provided for custom interactive elements.",
        "patterns": "- **Material Defaults**: Base accessibility provided by Flutter Material.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| flutter | sdk | Semantics tree |",
        "gaps": "- [ ] Explicit `Semantics` widgets should be added for custom interactive visual elements like charts.",
        "key_files": "| File | Purpose |\n|---|---|\n| N/A | N/A | No explicit a11y overrides found |"
    },
    {
        "file": "11-linting-formatting.md",
        "title": "Linting & Formatting",
        "overview": "The project uses standard Flutter linting rules to maintain code quality.",
        "sub_section": "Analysis Options",
        "details": "The `analysis_options.yaml` includes `package:flutter_lints/flutter.yaml`. Custom lint rules are mostly standard, ensuring a clean and consistent Dart codebase.",
        "patterns": "- **Standard Flutter Lints**: Encouraging good coding practices.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| flutter_lints | ^6.0.0 | Static analysis rules |",
        "gaps": "- [ ] Stricter rules (e.g., `always_specify_types` or `pedantic`) could be adopted for higher code quality.",
        "key_files": "| File | Purpose |\n|---|---|\n| [analysis_options.yaml](file:///Users/devashishraut/StudioProjects/workout_tracker/analysis_options.yaml) | Linter config |"
    },
    {
        "file": "12-pitfalls.md",
        "title": "Pitfalls & Tech Debt",
        "overview": "The legacy folder structure shows signs of a recent migration to Clean Architecture, leaving some technical debt.",
        "sub_section": "Legacy Files",
        "details": "There are duplicate legacy files present in the root `lib/` directory (e.g. `lib/screens/`, `lib/models/`, `lib/orm/`, `lib/services/`). These overlap with the organized `lib/domain/`, `lib/data/`, and `lib/ui/` folders.",
        "patterns": "- **Migration Artifacts**: Old folder structure remains alongside the new architecture.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| N/A | N/A | N/A |",
        "gaps": "- [ ] Delete legacy folders to prevent confusion and consolidate code.",
        "key_files": "| File | Purpose |\n|---|---|\n| lib/screens/ | Legacy UI folder to be removed |"
    },
    {
        "file": "13-build-tools.md",
        "title": "Build Tools & CI/CD",
        "overview": "The project uses standard Flutter build tooling.",
        "sub_section": "Build Configuration",
        "details": "Configuration is managed via `pubspec.yaml`. App versions are standard `1.0.0+1`. No explicit CI/CD pipelines (like GitHub Actions) were detected in the immediate root files scanned.",
        "patterns": "- **Standard Build**: Handled by Flutter CLI.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| N/A | N/A | N/A |",
        "gaps": "- [ ] Implement CI/CD workflows for automated testing and deployment.",
        "key_files": "| File | Purpose |\n|---|---|\n| [pubspec.yaml](file:///Users/devashishraut/StudioProjects/workout_tracker/pubspec.yaml) | Dependency and build config |"
    },
    {
        "file": "14-observability.md",
        "title": "Observability",
        "overview": "Observability is currently minimal, lacking extensive logging or analytics.",
        "sub_section": "Logging and Tracking",
        "details": "There are no traces of specialized logging frameworks or analytics packages in the `pubspec.yaml`.",
        "patterns": "- **No Observability**: Currently unmonitored in production context.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| N/A | N/A | N/A |",
        "gaps": "- [ ] Integrate logging (e.g. `logger` package) and analytics.",
        "key_files": "| File | Purpose |\n|---|---|\n| N/A | N/A | N/A |"
    },
    {
        "file": "15-offline-architecture.md",
        "title": "Offline Architecture",
        "overview": "The app is designed with a robust offline-first architecture using local caching and background sync to Google Drive.",
        "sub_section": "Sync Strategies",
        "details": "The application keeps a local representation of the Excel ORM and uses `AuthAndSyncUseCase` to handle manual and background syncing to Drive. `SharedPreferences` is used for localized, persistent state (like splits).",
        "patterns": "- **Offline-First**: Reads from local cache; writes sync asynchronously.\n- **Manual Sync Options**: `manualSyncToExcel()` for forcing updates.",
        "deps": "| Package | Version | Purpose |\n|---|---|---|\n| shared_preferences | ^2.5.3 | Local state persistence |",
        "gaps": "- [ ] Implementing conflict resolution when multiple devices update the same spreadsheet simultaneously.",
        "key_files": "| File | Purpose |\n|---|---|\n| [auth_and_sync_use_case.dart](file:///Users/devashishraut/StudioProjects/workout_tracker/lib/domain/use_cases/auth_and_sync_use_case.dart) | Sync logic |"
    }
]

for p in profiles:
    content = template.format(
        idx=p['file'].split('-')[0],
        title=p['title'],
        date=date_str,
        overview=p['overview'],
        sub_section=p['sub_section'],
        details=p['details'],
        patterns=p['patterns'],
        deps=p['deps'],
        gaps=p['gaps'],
        key_files=p['key_files']
    )
    with open(f"project-context/profiles/{p['file']}", "w") as f:
        f.write(content)

print("Generated 15 profiles.")
